[[constraint]]
  name = "github.com/bodokaiser/approx"
  version = "1.0.0"

[[constraint]]
  name = "github.com/labstack/echo"
  version = "3.3.5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "gopkg.in/alecthomas/kingpin.v2"
  version = "2.2.6"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.20.2"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.1"

[[constraint]]
  name = "periph.io/x/periph"
  version = "3.0.0"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.11.1"

[prune]
  go-tests = true
  unused-packages = true
