dds:
  sysclock: 1000000000
  refclock: 10000000
  pll: true
  sync: true
  spi3wire: true
  inversesinc: false

  spi:
    device: 'SPI1.0'
    maxfreq: 5000000

  gpio:
    reset: '65'
    update: '27'

mux:
  gpio:
    cs:
      - '48'
      - '30'
      - '60'
      - '31'
      - '50'
